package seed

import (
	"log"
    "fmt"
	"github.com/jinzhu/gorm"
	"wb2-master/api/models"
)

var countrys = []models.Country{
	models.Country{ID : 1,Code : "AF" ,Name : "Afghanistan",PhoneCode : 93},
    models.Country{ID : 2,Code : "AL" ,Name : "Albania",PhoneCode : 355},
    models.Country{ID : 3,Code : "DZ" ,Name : "Algeria",PhoneCode : 213},
    models.Country{ID : 4,Code : "AS" ,Name : "American Samoa",PhoneCode : 1684},
    models.Country{ID : 5,Code : "AD" ,Name : "Andorra",PhoneCode : 376},
    models.Country{ID : 6,Code : "AO" ,Name : "Angola",PhoneCode : 244},
    models.Country{ID : 7,Code : "AI" ,Name : "Anguilla",PhoneCode : 1264},
    models.Country{ID : 8,Code : "AQ" ,Name : "Antarctica",PhoneCode : 0},
    models.Country{ID : 9,Code : "AG" ,Name : "Antigua And Barbuda",PhoneCode : 1268},
    models.Country{ID : 10,Code : "AR",Name : "Argentina",PhoneCode : 54},
    models.Country{ID : 11,Code : "AM",Name : "Armenia",PhoneCode : 374},
    models.Country{ID : 12,Code : "AW",Name : "Aruba",PhoneCode : 297},
    models.Country{ID : 13,Code : "AU",Name : "Australia",PhoneCode : 61},
    models.Country{ID : 14,Code : "AT",Name : "Austria",PhoneCode : 43},
    models.Country{ID : 15,Code : "AZ",Name : "Azerbaijan",PhoneCode : 994},
    models.Country{ID : 16,Code : "BS",Name : "Bahamas The",PhoneCode : 1242},
    models.Country{ID : 17,Code : "BH",Name : "Bahrain",PhoneCode : 973},
    models.Country{ID : 18,Code : "BD",Name : "Bangladesh",PhoneCode : 880},
    models.Country{ID : 19,Code : "BB",Name : "Barbados",PhoneCode : 1246},
    models.Country{ID : 20,Code : "BY",Name : "Belarus",PhoneCode : 375},
    models.Country{ID : 21,Code : "BE",Name : "Belgium",PhoneCode : 32},
    models.Country{ID : 22,Code : "BZ",Name : "Belize",PhoneCode : 501},
    models.Country{ID : 23,Code : "BJ",Name : "Benin",PhoneCode : 229},
    models.Country{ID : 24,Code : "BM",Name : "Bermuda",PhoneCode : 1441},
    models.Country{ID : 25,Code : "BT",Name : "Bhutan",PhoneCode : 975},
    models.Country{ID : 26,Code : "BO",Name : "Bolivia",PhoneCode : 591},
    models.Country{ID : 27,Code : "BA",Name : "Bosnia and Herzegovina",PhoneCode : 387},
    models.Country{ID : 28,Code : "BW",Name : "Botswana",PhoneCode : 267},
    models.Country{ID : 29,Code : "BV",Name : "Bouvet Island",PhoneCode : 0},
    models.Country{ID : 30,Code : "BR",Name : "Brazil",PhoneCode : 55},
    models.Country{ID : 31,Code : "IO",Name : "British Indian Ocean Territory",PhoneCode : 246},
    models.Country{ID : 32,Code : "BN",Name : "Brunei",PhoneCode : 673},
    models.Country{ID : 33,Code : "BG",Name : "Bulgaria",PhoneCode : 359},
    models.Country{ID : 34,Code : "BF",Name : "Burkina Faso",PhoneCode : 226},
    models.Country{ID : 35,Code : "BI",Name : "Burundi",PhoneCode : 257},
    models.Country{ID : 36,Code : "KH",Name : "Cambodia",PhoneCode : 855},
    models.Country{ID : 37,Code : "CM",Name : "Cameroon",PhoneCode : 237},
    models.Country{ID : 38,Code : "CA",Name : "Canada",PhoneCode : 1},
    models.Country{ID : 39,Code : "CV",Name : "Cape Verde",PhoneCode : 238},
    models.Country{ID : 40,Code : "KY",Name : "Cayman Islands",PhoneCode : 1345},
    models.Country{ID : 41,Code : "CF",Name : "Central African Republic",PhoneCode : 236},
    models.Country{ID : 42,Code : "TD",Name : "Chad",PhoneCode : 235},
    models.Country{ID : 43,Code : "CL",Name : "Chile",PhoneCode : 56},
    models.Country{ID : 44,Code : "CN",Name : "China",PhoneCode : 86},
    models.Country{ID : 45,Code : "CX",Name : "Christmas Island",PhoneCode : 61},
    models.Country{ID : 46,Code : "CC",Name : "Cocos (Keeling} Islands",PhoneCode : 672},
    models.Country{ID : 47,Code : "CO",Name : "Colombia",PhoneCode : 57},
    models.Country{ID : 48,Code : "KM",Name : "Comoros",PhoneCode : 269},
    models.Country{ID : 49,Code : "CG",Name : "Congo",PhoneCode : 242},
    models.Country{ID : 50,Code : "CD",Name : "Congo The Democratic Republic Of The",PhoneCode : 242},
    models.Country{ID : 51,Code : "CK",Name : "Cook Islands",PhoneCode : 682},
    models.Country{ID : 52,Code : "CR",Name : "Costa Rica",PhoneCode : 506},
    models.Country{ID : 53,Code : "CI",Name : "Cote D Ivoire (Ivory Coast}",PhoneCode : 225},
    models.Country{ID : 54,Code : "HR",Name : "Croatia (Hrvatska}",PhoneCode : 385},
    models.Country{ID : 55,Code : "CU",Name : "Cuba",PhoneCode : 53},
    models.Country{ID : 56,Code : "CY",Name : "Cyprus",PhoneCode : 357},
    models.Country{ID : 57,Code : "CZ",Name : "Czech Republic",PhoneCode : 420},
    models.Country{ID : 58,Code : "DK",Name : "Denmark",PhoneCode : 45},
    models.Country{ID : 59,Code : "DJ",Name : "Djibouti",PhoneCode : 253},
    models.Country{ID : 60,Code : "DM",Name : "Dominica",PhoneCode : 1767},
    models.Country{ID : 61,Code : "DO",Name : "Dominican Republic",PhoneCode : 1809},
    models.Country{ID : 62,Code : "TP",Name : "East Timor",PhoneCode : 670},
    models.Country{ID : 63,Code : "EC",Name : "Ecuador",PhoneCode : 593},
    models.Country{ID : 64,Code : "EG",Name : "Egypt",PhoneCode : 20},
    models.Country{ID : 65,Code : "SV",Name : "El Salvador",PhoneCode : 503},
    models.Country{ID : 66,Code : "GQ",Name : "Equatorial Guinea",PhoneCode : 240},
    models.Country{ID : 67,Code : "ER",Name : "Eritrea",PhoneCode : 291},
    models.Country{ID : 68,Code : "EE",Name : "Estonia",PhoneCode : 372},
    models.Country{ID : 69,Code : "ET",Name : "Ethiopia",PhoneCode : 251},
    models.Country{ID : 70,Code : "XA",Name : "External Territories of Australia",PhoneCode : 61},
    models.Country{ID : 71,Code : "FK",Name : "Falkland Islands",PhoneCode : 500},
    models.Country{ID : 72,Code : "FO",Name : "Faroe Islands",PhoneCode : 298},
    models.Country{ID : 73,Code : "FJ",Name : "Fiji Islands",PhoneCode : 679},
    models.Country{ID : 74,Code : "FI",Name : "Finland",PhoneCode : 358},
    models.Country{ID : 75,Code : "FR",Name : "France",PhoneCode : 33},
    models.Country{ID : 76,Code : "GF",Name : "French Guiana",PhoneCode : 594},
    models.Country{ID : 77,Code : "PF",Name : "French Polynesia",PhoneCode : 689},
    models.Country{ID : 78,Code : "TF",Name : "French Southern Territories",PhoneCode : 0},
    models.Country{ID : 79,Code : "GA",Name : "Gabon",PhoneCode : 241},
    models.Country{ID : 80,Code : "GM",Name : "Gambia The",PhoneCode : 220},
    models.Country{ID : 81,Code : "GE",Name : "Georgia",PhoneCode : 995},
    models.Country{ID : 82,Code : "DE",Name : "Germany",PhoneCode : 49},
    models.Country{ID : 83,Code : "GH",Name : "Ghana",PhoneCode : 233},
    models.Country{ID : 84,Code : "GI",Name : "Gibraltar",PhoneCode : 350},
    models.Country{ID : 85,Code : "GR",Name : "Greece",PhoneCode : 30},
    models.Country{ID : 86,Code : "GL",Name : "Greenland",PhoneCode : 299},
    models.Country{ID : 87,Code : "GD",Name : "Grenada",PhoneCode : 1473},
    models.Country{ID : 88,Code : "GP",Name : "Guadeloupe",PhoneCode : 590},
    models.Country{ID : 89,Code : "GU",Name : "Guam",PhoneCode : 1671},
    models.Country{ID : 90,Code : "GT",Name : "Guatemala",PhoneCode : 502},
    models.Country{ID : 91,Code : "XU",Name : "Guernsey and Alderney",PhoneCode : 44},
    models.Country{ID : 92,Code : "GN",Name : "Guinea",PhoneCode : 224},
    models.Country{ID : 93,Code : "GW",Name : "Guinea-Bissau",PhoneCode : 245},
    models.Country{ID : 94,Code : "GY",Name : "Guyana",PhoneCode : 592},
    models.Country{ID : 95,Code : "HT",Name : "Haiti",PhoneCode : 509},
    models.Country{ID : 96,Code : "HM",Name : "Heard and McDonald Islands",PhoneCode : 0},
    models.Country{ID : 97,Code : "HN",Name : "Honduras",PhoneCode : 504},
    models.Country{ID : 98,Code : "HK",Name : "Hong Kong S.A.R.",PhoneCode : 852},
    models.Country{ID : 99,Code : "HU",Name : "Hungary",PhoneCode : 36},
    models.Country{ID : 100,Code : "IS",Name : "Iceland",PhoneCode : 354},
    models.Country{ID : 101,Code : "IN",Name : "India",PhoneCode : 91},
    models.Country{ID : 102,Code : "ID",Name : "Indonesia",PhoneCode : 62},
    models.Country{ID : 103,Code : "IR",Name : "Iran",PhoneCode : 98},
    models.Country{ID : 104,Code : "IQ",Name : "Iraq",PhoneCode : 964},
    models.Country{ID : 105,Code : "IE",Name : "Ireland",PhoneCode : 353},
    models.Country{ID : 106,Code : "IL",Name : "Israel",PhoneCode : 972},
    models.Country{ID : 107,Code : "IT",Name : "Italy",PhoneCode : 39},
    models.Country{ID : 108,Code : "JM",Name : "Jamaica",PhoneCode : 1876},
    models.Country{ID : 109,Code : "JP",Name : "Japan",PhoneCode : 81},
    models.Country{ID : 110,Code : "XJ",Name : "Jersey",PhoneCode : 44},
    models.Country{ID : 111,Code : "JO",Name : "Jordan",PhoneCode : 962},
    models.Country{ID : 112,Code : "KZ",Name : "Kazakhstan",PhoneCode : 7},
    models.Country{ID : 113,Code : "KE",Name : "Kenya",PhoneCode : 254},
    models.Country{ID : 114,Code : "KI",Name : "Kiribati",PhoneCode : 686},
    models.Country{ID : 115,Code : "KP",Name : "Korea North",PhoneCode : 850},
    models.Country{ID : 116,Code : "KR",Name : "Korea South",PhoneCode : 82},
    models.Country{ID : 117,Code : "KW",Name : "Kuwait",PhoneCode : 965},
    models.Country{ID : 118,Code : "KG",Name : "Kyrgyzstan",PhoneCode : 996},
    models.Country{ID : 119,Code : "LA",Name : "Laos",PhoneCode : 856},
    models.Country{ID : 120,Code : "LV",Name : "Latvia",PhoneCode : 371},
    models.Country{ID : 121,Code : "LB",Name : "Lebanon",PhoneCode : 961},
    models.Country{ID : 122,Code : "LS",Name : "Lesotho",PhoneCode : 266},
    models.Country{ID : 123,Code : "LR",Name : "Liberia",PhoneCode : 231},
    models.Country{ID : 124,Code : "LY",Name : "Libya",PhoneCode : 218},
    models.Country{ID : 125,Code : "LI",Name : "Liechtenstein",PhoneCode : 423},
    models.Country{ID : 126,Code : "LT",Name : "Lithuania",PhoneCode : 370},
    models.Country{ID : 127,Code : "LU",Name : "Luxembourg",PhoneCode : 352},
    models.Country{ID : 128,Code : "MO",Name : "Macau S.A.R.",PhoneCode : 853},
    models.Country{ID : 129,Code : "MK",Name : "Macedonia",PhoneCode : 389},
    models.Country{ID : 130,Code : "MG",Name : "Madagascar",PhoneCode : 261},
    models.Country{ID : 131,Code : "MW",Name : "Malawi",PhoneCode : 265},
    models.Country{ID : 132,Code : "MY",Name : "Malaysia",PhoneCode : 60},
    models.Country{ID : 133,Code : "MV",Name : "Maldives",PhoneCode : 960},
    models.Country{ID : 134,Code : "ML",Name : "Mali",PhoneCode : 223},
    models.Country{ID : 135,Code : "MT",Name : "Malta",PhoneCode : 356},
    models.Country{ID : 136,Code : "XM",Name : "Man (Isle of}",PhoneCode : 44},
    models.Country{ID : 137,Code : "MH",Name : "Marshall Islands",PhoneCode : 692},
    models.Country{ID : 138,Code : "MQ",Name : "Martinique",PhoneCode : 596},
    models.Country{ID : 139,Code : "MR",Name : "Mauritania",PhoneCode : 222},
    models.Country{ID : 140,Code : "MU",Name : "Mauritius",PhoneCode : 230},
    models.Country{ID : 141,Code : "YT",Name : "Mayotte",PhoneCode : 269},
    models.Country{ID : 142,Code : "MX",Name : "Mexico",PhoneCode : 52},
    models.Country{ID : 143,Code : "FM",Name : "Micronesia",PhoneCode : 691},
    models.Country{ID : 144,Code : "MD",Name : "Moldova",PhoneCode : 373},
    models.Country{ID : 145,Code : "MC",Name : "Monaco",PhoneCode : 377},
    models.Country{ID : 146,Code : "MN",Name : "Mongolia",PhoneCode : 976},
    models.Country{ID : 147,Code : "MS",Name : "Montserrat",PhoneCode : 1664},
    models.Country{ID : 148,Code : "MA",Name : "Morocco",PhoneCode : 212},
    models.Country{ID : 149,Code : "MZ",Name : "Mozambique",PhoneCode : 258},
    models.Country{ID : 150,Code : "MM",Name : "Myanmar",PhoneCode : 95},
    models.Country{ID : 151,Code : "NA",Name : "Namibia",PhoneCode : 264},
    models.Country{ID : 152,Code : "NR",Name : "Nauru",PhoneCode : 674},
    models.Country{ID : 153,Code : "NP",Name : "Nepal",PhoneCode : 977},
    models.Country{ID : 154,Code : "AN",Name : "Netherlands Antilles",PhoneCode : 599},
    models.Country{ID : 155,Code : "NL",Name : "Netherlands The",PhoneCode : 31},
    models.Country{ID : 156,Code : "NC",Name : "New Caledonia",PhoneCode : 687},
    models.Country{ID : 157,Code : "NZ",Name : "New Zealand",PhoneCode : 64},
    models.Country{ID : 158,Code : "NI",Name : "Nicaragua",PhoneCode : 505},
    models.Country{ID : 159,Code : "NE",Name : "Niger",PhoneCode : 227},
    models.Country{ID : 160,Code : "NG",Name : "Nigeria",PhoneCode : 234},
    models.Country{ID : 161,Code : "NU",Name : "Niue",PhoneCode : 683},
    models.Country{ID : 162,Code : "NF",Name : "Norfolk Island",PhoneCode : 672},
    models.Country{ID : 163,Code : "MP",Name : "Northern Mariana Islands",PhoneCode : 1670},
    models.Country{ID : 164,Code : "NO",Name : "Norway",PhoneCode : 47},
    models.Country{ID : 165,Code : "OM",Name : "Oman",PhoneCode : 968},
    models.Country{ID : 166,Code : "PK",Name : "Pakistan",PhoneCode : 92},
    models.Country{ID : 167,Code : "PW",Name : "Palau",PhoneCode : 680},
    models.Country{ID : 168,Code : "PS",Name : "Palestinian Territory Occupied",PhoneCode : 970},
    models.Country{ID : 169,Code : "PA",Name : "Panama",PhoneCode : 507},
    models.Country{ID : 170,Code : "PG",Name : "Papua new Guinea",PhoneCode : 675},
    models.Country{ID : 171,Code : "PY",Name : "Paraguay",PhoneCode : 595},
    models.Country{ID : 172,Code : "PE",Name : "Peru",PhoneCode : 51},
    models.Country{ID : 173,Code : "PH",Name : "Philippines",PhoneCode : 63},
    models.Country{ID : 174,Code : "PN",Name : "Pitcairn Island",PhoneCode : 0},
    models.Country{ID : 175,Code : "PL",Name : "Poland",PhoneCode : 48},
    models.Country{ID : 176,Code : "PT",Name : "Portugal",PhoneCode : 351},
    models.Country{ID : 177,Code : "PR",Name : "Puerto Rico",PhoneCode : 1787},
    models.Country{ID : 178,Code : "QA",Name : "Qatar",PhoneCode : 974},
    models.Country{ID : 179,Code : "RE",Name : "Reunion",PhoneCode : 262},
    models.Country{ID : 180,Code : "RO",Name : "Romania",PhoneCode : 40},
    models.Country{ID : 181,Code : "RU",Name : "Russia",PhoneCode : 70},
    models.Country{ID : 182,Code : "RW",Name : "Rwanda",PhoneCode : 250},
    models.Country{ID : 183,Code : "SH",Name : "Saint Helena",PhoneCode : 290},
    models.Country{ID : 184,Code : "KN",Name : "Saint Kitts And Nevis",PhoneCode : 1869},
    models.Country{ID : 185,Code : "LC",Name : "Saint Lucia",PhoneCode : 1758},
    models.Country{ID : 186,Code : "PM",Name : "Saint Pierre and Miquelon",PhoneCode : 508},
    models.Country{ID : 187,Code : "VC",Name : "Saint Vincent And The Grenadines",PhoneCode : 1784},
    models.Country{ID : 188,Code : "WS",Name : "Samoa",PhoneCode : 684},
    models.Country{ID : 189,Code : "SM",Name : "San Marino",PhoneCode : 378},
    models.Country{ID : 190,Code : "ST",Name : "Sao Tome and Principe",PhoneCode : 239},
    models.Country{ID : 191,Code : "SA",Name : "Saudi Arabia",PhoneCode : 966},
    models.Country{ID : 192,Code : "SN",Name : "Senegal",PhoneCode : 221},
    models.Country{ID : 193,Code : "RS",Name : "Serbia",PhoneCode : 381},
    models.Country{ID : 194,Code : "SC",Name : "Seychelles",PhoneCode : 248},
    models.Country{ID : 195,Code : "SL",Name : "Sierra Leone",PhoneCode : 232},
    models.Country{ID : 196,Code : "SG",Name : "Singapore",PhoneCode : 65},
    models.Country{ID : 197,Code : "SK",Name : "Slovakia",PhoneCode : 421},
    models.Country{ID : 198,Code : "SI",Name : "Slovenia",PhoneCode : 386},
    models.Country{ID : 199,Code : "XG",Name : "Smaller Territories of the UK",PhoneCode : 44},
    models.Country{ID : 200,Code : "SB",Name : "Solomon Islands",PhoneCode : 677},
    models.Country{ID : 201,Code : "SO",Name : "Somalia",PhoneCode : 252},
    models.Country{ID : 202,Code : "ZA",Name : "South Africa",PhoneCode : 27},
    models.Country{ID : 203,Code : "GS",Name : "South Georgia",PhoneCode : 0},
    models.Country{ID : 204,Code : "SS",Name : "South Sudan",PhoneCode : 211},
    models.Country{ID : 205,Code : "ES",Name : "Spain",PhoneCode : 34},
    models.Country{ID : 206,Code : "LK",Name : "Sri Lanka",PhoneCode : 94},
    models.Country{ID : 207,Code : "SD",Name : "Sudan",PhoneCode : 249},
    models.Country{ID : 208,Code : "SR",Name : "Suriname",PhoneCode : 597},
    models.Country{ID : 209,Code : "SJ",Name : "Svalbard And Jan Mayen Islands",PhoneCode : 47},
    models.Country{ID : 210,Code : "SZ",Name : "Swaziland",PhoneCode : 268},
    models.Country{ID : 211,Code : "SE",Name : "Sweden",PhoneCode : 46},
    models.Country{ID : 212,Code : "CH",Name : "Switzerland",PhoneCode : 41},
    models.Country{ID : 213,Code : "SY",Name : "Syria",PhoneCode : 963},
    models.Country{ID : 214,Code : "TW",Name : "Taiwan",PhoneCode : 886},
    models.Country{ID : 215,Code : "TJ",Name : "Tajikistan",PhoneCode : 992},
    models.Country{ID : 216,Code : "TZ",Name : "Tanzania",PhoneCode : 255},
    models.Country{ID : 217,Code : "TH",Name : "Thailand",PhoneCode : 66},
    models.Country{ID : 218,Code : "TG",Name : "Togo",PhoneCode : 228},
    models.Country{ID : 219,Code : "TK",Name : "Tokelau",PhoneCode : 690},
    models.Country{ID : 220,Code : "TO",Name : "Tonga",PhoneCode : 676},
    models.Country{ID : 221,Code : "TT",Name : "Trinidad And Tobago",PhoneCode : 1868},
    models.Country{ID : 222,Code : "TN",Name : "Tunisia",PhoneCode : 216},
    models.Country{ID : 223,Code : "TR",Name : "Turkey",PhoneCode : 90},
    models.Country{ID : 224,Code : "TM",Name : "Turkmenistan",PhoneCode : 7370},
    models.Country{ID : 225,Code : "TC",Name : "Turks And Caicos Islands",PhoneCode : 1649},
    models.Country{ID : 226,Code : "TV",Name : "Tuvalu",PhoneCode : 688},
    models.Country{ID : 227,Code : "UG",Name : "Uganda",PhoneCode : 256},
    models.Country{ID : 228,Code : "UA",Name : "Ukraine",PhoneCode : 380},
    models.Country{ID : 229,Code : "AE",Name : "United Arab Emirates",PhoneCode : 971},
    models.Country{ID : 230,Code : "GB",Name : "United Kingdom",PhoneCode : 44},
    models.Country{ID : 231,Code : "US",Name : "United States",PhoneCode : 1},
    models.Country{ID : 232,Code : "UM",Name : "United States Minor Outlying Islands",PhoneCode : 1},
    models.Country{ID : 233,Code : "UY",Name : "Uruguay",PhoneCode : 598},
    models.Country{ID : 234,Code : "UZ",Name : "Uzbekistan",PhoneCode : 998},
    models.Country{ID : 235,Code : "VU",Name : "Vanuatu",PhoneCode : 678},
    models.Country{ID : 236,Code : "VA",Name : "Vatican City State (Holy See}",PhoneCode : 39},
    models.Country{ID : 237,Code : "VE",Name : "Venezuela",PhoneCode : 58},
    models.Country{ID : 238,Code : "VN",Name : "Vietnam",PhoneCode : 84},
    models.Country{ID : 239,Code : "VG",Name : "Virgin Islands (British}",PhoneCode : 1284},
    models.Country{ID : 240,Code : "VI",Name : "Virgin Islands (US}",PhoneCode : 1340},
    models.Country{ID : 241,Code : "WF",Name : "Wallis And Futuna Islands",PhoneCode : 681},
    models.Country{ID : 242,Code : "EH",Name : "Western Sahara",PhoneCode : 212},
    models.Country{ID : 243,Code : "YE",Name : "Yemen",PhoneCode : 967},
    models.Country{ID : 244,Code : "YU",Name : "Yugoslavia",PhoneCode : 38},
    models.Country{ID : 245,Code : "ZM",Name : "Zambia",PhoneCode : 260},
    models.Country{ID : 246,Code : "ZW",Name : "Zimbabwe",PhoneCode : 263},
}

func CountrySeed(db *gorm.DB) {
	var err error
	//country
	for i, _ := range countrys {
		err = db.Model(&models.Country{}).Create(&countrys[i]).Error
		if err != nil {
			log.Fatalf("cannot seed country table: %v", err)
		}
    }
	fmt.Println("Success seed country table")
}